/**
 * 存放分发action的type常量
 */
export const type = {
    SWITCH_BREADCRUMB_FIRST : 'SWITCH_BREADCRUMB_FIRST',
    SWITCH_BREADCRUMB_REST : 'SWITCH_BREADCRUMB_REST',
	CHANGE_HEADER_MENU_KEY:'CHANGE_HEADER_MENU_KEY',
	CHANGE_LEFT_NAV_KEY:'CHANGE_LEFT_NAV_KEY',
	USER_INFO:'USER_INFO'
}
